# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-07 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='no_of_songs',
            new_name='genre',
        ),
    ]
